# Generated by Django 4.1.7 on 2023-03-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('sunbeds', models.PositiveSmallIntegerField()),
                ('row', models.SmallIntegerField(default=0)),
                ('column', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('customer', models.TextField(blank=True)),
                ('sunbeds', models.PositiveSmallIntegerField(default=2)),
                ('type', models.CharField(choices=[('S', 'seasonal'), ('P', 'periodic'), ('C', 'custom')], default='S', max_length=1)),
                ('custom_period', models.CharField(blank=True, default='', max_length=30)),
                ('deposit', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('umbrella', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.umbrella')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.TextField(blank=True)),
                ('sunbeds', models.PositiveSmallIntegerField(default=2)),
                ('date', models.DateField(blank=True)),
                ('paid', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subscription')),
                ('umbrella', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.umbrella')),
            ],
        ),
    ]
