# Generated by Django 3.2 on 2021-05-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umbrella',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='umbrella',
            name='pos_y',
        ),
        migrations.RemoveField(
            model_name='umbrella',
            name='state',
        ),
        migrations.AddField(
            model_name='umbrella',
            name='row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
