# Generated by Django 3.2 on 2021-05-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210526_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrella',
            name='row',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('customer', models.TextField()),
                ('beachLoungers', models.SmallIntegerField()),
                ('subscriptionType', models.CharField(choices=[('S', 'seasonal'), ('P', 'periodic'), ('C', 'custom')], max_length=1)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('paid', models.BooleanField()),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.umbrella')),
            ],
        ),
    ]
