# Generated by Django 3.2 on 2021-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210526_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='beachLoungers',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='umbrella',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='umbrella',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
