# Generated by Django 3.2 on 2021-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210526_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='beachLoungers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
