# Generated by Django 3.2 on 2021-05-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subscription_beachloungers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('S', 'seasonal'), ('P', 'periodic'), ('C', 'custom')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='umbrella',
            name='row',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.TextField(blank=True)),
                ('beachLoungers', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField(blank=True)),
                ('paid', models.BooleanField(null=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subscription')),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.umbrella')),
            ],
        ),
    ]
