# Generated by Django 3.2 on 2021-05-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210526_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='dateR',
        ),
    ]
