# Generated by Django 3.2 on 2021-05-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_date_reservation_dater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='dateR',
            new_name='date',
        ),
    ]
