# Generated by Django 4.1.7 on 2023-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
