# Generated by Django 3.2 on 2021-06-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_subscription_umbrella'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umbrella',
            name='code',
        ),
    ]
