# Generated by Django 3.2 on 2021-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_umbrella_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
