# Generated by Django 3.2 on 2021-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_period',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('S', 'seasonal'), ('P', 'periodic'), ('C', 'custom')], default='S', max_length=1),
        ),
    ]
