# Generated by Django 3.2 on 2021-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210614_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='custom_period',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
