# Generated by Django 3.2 on 2021-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_subscription_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='deposit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
