# Generated by Django 3.2 on 2021-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210615_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrella',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
