# Generated by Django 3.2 on 2021-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_umbrella_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrella',
            name='beachLoungers',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='beachLoungers',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
