# Generated by Django 3.2 on 2021-06-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_umbrella_beachloungers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
