version: '3'
services:

  frontend:
    image: manage-beach-umbrellas-fe:latest
    container_name: manage-beach-umbrellas-fe
    restart: always
    volumes:
      - ./frontend/:/frontend
      - node_modules:/frontend/node_modules
    env_file:
      - .env.dev
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    image: manage-beach-umbrellas-be:latest
    container_name: manage-beach-umbrellas-be
    restart: always
    volumes:
      - ./backend/:/src
      - sqlite_data:/src/database
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - backend
      - frontend
volumes:
  static:
  media:
  node_modules:
  sqlite_data: