# Generated by Django 4.1.7 on 2023-04-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='category',
            field=models.CharField(choices=[('R', 'reservation'), ('S', 'subscription'), ('C', 'constant')], default='R', max_length=1),
        ),
    ]
