# Generated by Django 4.1.7 on 2023-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subscription_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
