# Generated by Django 4.1.7 on 2023-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='code',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
