# Generated by Django 4.1.7 on 2023-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_code_subscription_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
