# Generated by Django 3.2.18 on 2024-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_custom_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
