# Generated by Django 3.2.18 on 2024-03-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_umbrella_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
    ]
