# Generated by Django 3.2.18 on 2024-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_season_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('code', 'season'), name='unique_code_within_season'),
        ),
    ]
