# Generated by Django 3.2.18 on 2024-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_season_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constant',
        ),
        migrations.AlterField(
            model_name='audit',
            name='category',
            field=models.CharField(choices=[('R', 'reservation'), ('S', 'subscription')], default='R', max_length=1),
        ),
    ]
